SwapFashions/Bid/urls.py
from django.urls import path,re_path
from Bid.views import CreateController,DeleteController



app_name='Bid'
urlpatterns = [
    re_path(r'^$', CreateController, name='create'),
    re_path(r'^delete/$', DeleteController, name='delete' )
        
    ]

SwapFashions/SwapFashions/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from rest_framework_simplejwt import views as jwt_views
from django.views.generic import TemplateView


# from rest_framework_swagger.views import get_swagger_view
# from rest_framework.schemas import get_schema_view

# schema_view = get_swagger_view(title='Swap Fashin API')


urlpatterns = [
    # path('docs/', include('rest_framework_docs.urls')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('apis/', include('apis.urls')),
    path('', include('swap_fashions.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/', include('auth.urls')),
    path("contact/", include('contactus.urls')),
    path('razorpay/', include('razorpay.urls')),
    path('user/', include('Users.urls', namespace='Users')),
    path('bid/', include('Bid.urls', namespace='Bid')),
    path('api/v1/', include('swap_fashion_apis.urls')),

    # # swagger api docs
    # path('docs', schema_view),
    # path('openapi', get_schema_view(
    #     title="Swap Fashion",
    #     description="API for all things …", 
    #     version="1.0.0"), name='openapi-schema'),
    # path('api-docs/', TemplateView.as_view(template_name='swagger-ui.html',
    #                                        extra_context={'schema_url':'openapi-schema'}
    #                                        ), name='swagger-ui'),
    # path('redoc/', TemplateView.as_view(
    #     template_name='redoc.html',
    #     extra_context={'schema_url':'openapi-schema'}), name='redoc'),



]


"""
1) title not coming correct
SF(swap fashions)22(year)02(month)29(code)C(size code) (serial Number )
"""


# admin conf
admin.site.site_header = 'Swap Fashions'
admin.site.index_title = 'Swap Fashions'
admin.site.site_title = 'Swap Fashions'

SwapFashions/Users/urls.py
from django.urls import path,re_path
from Users.views import SignUpController,SignInController,HomePageController,LogOutController



app_name='Users'
urlpatterns = [
    re_path(r'^sign-in/$', SignInController, name='sign-in'),
    re_path(r'^sign-up/$', SignUpController, name='sign-up' ),
    re_path(r'^home-page/$',  HomePageController, name='home-page'),
    re_path(r'^log-out/$',  LogOutController, name='log-out'),

    
    ]

SwapFashions/jet/urls.py
import django
try:
    from django.conf.urls import url
except ImportError: # Django 3+ (tested with Django 4.0)
    from django.urls import re_path as url

try:
    from django.views.i18n import JavaScriptCatalog
    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.views import add_bookmark_view, remove_bookmark_view, toggle_application_pin_view, model_lookup_view


app_name = 'jet'

urlpatterns = [
    url(
        r'^add_bookmark/$',
        add_bookmark_view,
        name='add_bookmark'
    ),
    url(
        r'^remove_bookmark/$',
        remove_bookmark_view,
        name='remove_bookmark'
    ),
    url(
        r'^toggle_application_pin/$',
        toggle_application_pin_view,
        name='toggle_application_pin'
    ),
    url(
        r'^model_lookup/$',
        model_lookup_view,
        name='model_lookup'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'django.contrib.admin+jet'},
        name='jsi18n'
    ),
]

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)

SwapFashions/Users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                related_name='customer',
                                on_delete=models.CASCADE)
    # created customer models cus its extendable and also seperate from admin
    



class TwoFactorAuthentication(models.Model):
    """
    TwoFactorAuthentication
    mobile and email 
    authentication module
    """
    twoFA_type = models.CharField(
        max_length=20,
        choices=(
            ('link', 'link'),
            ('otp', 'OTP'),
        )
    )
    activation_link = models.TextField(null=True, blank=True)
    otp = models.PositiveIntegerField(null=True)
    delivery_status = models.CharField(
        max_length=20,
        choices=(
            ('delivered', 'Delivered'),
            ('not_delivered', 'Not Delivered'),
            ('successful', 'Successful'),
            ('expired', 'Expired')
        )
    )
    user_type = models.CharField(
        max_length=20,
        choices=(
            ('customer', 'Customer'), ('admin', 'Admin'),
        )
    )
    auth_type = models.CharField(
        max_length=20,
        choices=(
            ('phone', 'Phone Number'), ('email', 'Email ID')
        )
    )

    # verification flags

    created_at = models.DateTimeField(auto_now_add=True)
    expired_datetime = models.DateTimeField(verbose_name="Expired At")
    is_verified = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = '  Two Factor Authentication'
        verbose_name_plural = '  Two Factor Authentication'
        db_table = 'two_factor_authentication'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.otp)

    def get_user_name(self):
        """
        created at 2021-08-31 by Gourav Sharma (^_^) get_user_name
        This "get_user_name" method used to get the username to get the username
        return: (username)
        """
        if self.user:
            return str(self.user.username) if self.user.username else '-'
        else:
            return '-'

    get_user_name.short_description = 'Email'

SwapFashions/Users/forms.py
from django import forms
from django.contrib.auth.models import User




class CustomerForm(forms.Form):
    first_name = forms.CharField(max_length=200,       
                             label=False,
                             widget=forms.TextInput(
                               attrs={'id':'first_name',
                                      'class': '',
                                      'placeholder':'First Name'}))
    last_name = forms.CharField(max_length=200,       
                             label=False,
                             widget=forms.TextInput(
                               attrs={'id':'last_name',
                                      'class': '',
                                      'placeholder':'Last Name'}))
    username = forms.CharField(max_length=20,       
                             label=False,
                             widget=forms.TextInput(
                               attrs={'id':'username',
                                      'class': '',
                                      'placeholder':'Username'}))
    email    = forms.EmailField(max_length=250,
                                label =False,
                                widget=forms.EmailInput(
                                      attrs={'id':'email',
                                            'class': '',
                                            'placeholder':'E-mail'}))

    password = forms.CharField(max_length=30,
                               label=False,
                               widget=forms.PasswordInput(
                                      attrs={'id':'password',
                                            'placeholder':'Enter password',
                                            'class':''}))
    password2 = forms.CharField(max_length=30,
                               label=False,
                               widget=forms.PasswordInput(
                                      attrs={'id':'password2',
                                            'placeholder':'Repeat password',
                                            'class':''}))

    def clean_email(self):
        # cd == Cleaned_data
        cd = self.cleaned_data.get('email')
        cd = cd.lower()
        user = User.objects.filter(email=cd).exists()
        if user:
            raise forms.ValidationError('This e-mail address is already registered to another account')
        return cd



    def clean_username(self):
        cd = self.cleaned_data.get('username')
        cd = cd.lower()
        if len(cd) < 6:
            raise forms.ValidationError("Username must contain up to 6 characters")
        if ' ' in cd:
            raise forms.ValidationError("A blank space can not be included as part of username")
        user = User.objects.filter(username=cd).exists()
        if user:
            raise forms.ValidationError('Username is already taken. Please choose another username')
        return cd

  

    def clean(self):
        cleaned_data = super(CustomerForm, self).clean()
        first_password = self.cleaned_data.get('password')
        second_password = self.cleaned_data.get('password2')
        if first_password != second_password:
            self.add_error('password',"Passwords did not match")
        return cleaned_data



class SignInForm(forms.Form):
    
    email    = forms.EmailField(max_length=250,
                                label =False,
                                widget=forms.EmailInput(
                                      attrs={'id':'email',
                                            'class': '',
                                            'placeholder':'E-mail'}))
    password = forms.CharField(max_length=30,
                               label=False,
                               widget=forms.PasswordInput(
                                      attrs={'id':'password',
                                            'placeholder':'Enter password',
                                            'class':''}))
    def __init__(self,*args,**kwargs):
        super(SignInForm,self).__init__(*args,**kwargs)

    def clean_email(self):
        # cd == Cleaned_data
        cd = self.cleaned_data.get('email')
        cd = cd.lower()
        user = User.objects.filter(email=cd).exists()
        if not user:
            raise forms.ValidationError('Email address and password did not match')
        return cd
    def clean(self):
        cleaned_data = super(SignInForm, self).clean()
        return cleaned_data
  

   

SwapFashions/Users/views.py
from django.shortcuts import render,redirect
from Users.forms import CustomerForm,SignInForm
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.urls import reverse
from django.contrib.auth import login,logout
from django.contrib.auth.models import User
from Users.models import Customer
from Coins.models import Coin


from django.contrib.auth.decorators import login_required



# Create your views here.

def SignUpController(request):
	if request.method == "POST":
		post_form = CustomerForm(request.POST)
		if post_form.is_valid():
			cd = post_form.cleaned_data
			user = User.objects.create_user(username=cd['username'],
			        						password=cd['password'],
			      				  			first_name = cd['first_name'],
			        						last_name=cd['last_name'],
			        						email=cd['email'])
			Customer.objects.create(user=user)
			login(request,user)
			request.session["new"] = True
			return HttpResponseRedirect(reverse('Users:home-page'))
		else:
			return render(request,'Users/sign_up.html',{'form':post_form})
	else:
		form = CustomerForm()
		return render(request,'Users/sign_up.html',
                          {'form':form})


def SignInController(request):
	if request.method == "POST":
		post_form = SignInForm(request.POST)
		if post_form.is_valid():
			cd = post_form.cleaned_data
			user = User.objects.get(email=cd['email'])
			checker = user.check_password(cd['password']) 
			if checker:
				login(request, user)
				return HttpResponseRedirect(reverse('Users:home-page'))
			else:
				post_form.add_error('email','Email and password did not match')
				return render(request,'Users/sign_in.html',
                        {'form':post_form})
		else:
			return render(request,'Users/sign_in.html',
                          {'form':post_form})
	else:
		if request.user.is_authenticated:
			return HttpResponseRedirect(reverse('Users:home-page'))
		form = SignInForm()
		return render(request,'Users/sign_in.html',
                          {'form':form})
def LogOutController(request):
	logout(request)
	return HttpResponseRedirect(reverse('Users:sign-in'))
		
@login_required
def HomePageController(request):
	customer = request.user.customer
	coin=Coin.objects.get(name="MillionToken")
	try:
		bid = customer.bid
	except ObjectDoesNotExist:
		bid = False

	return render(request,'Users/home_page.html',
											{'coin':coin,
											'bid':bid})


def HomeRedirectController(request):
	return HttpResponseRedirect(reverse('Users:sign-in'))

SwapFashions/Users/templates/Users/base.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
<head>
	<meta charset="utf-8">
	<title > DigiCentra </title>
	<meta name="theme-color" content="#ffffff">
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no ">
	{% block head %}{% endblock %}
</head>
<body>
	
	


	{% block content %}{% endblock %}


</body>
</html>

SwapFashions/Users/templates/Users/home_page.html
{% extends 'Users/base.html' %}
{% block content %}

<style type="text/css">
    .lorange{
        color: orange;
        /*font-weight: bold;*/
        text-align: center;
        font-size: 130%;
    }
    .lblue{
        color: blue;
        /*font-weight: bold;*/
    }
    .cover{
        border-radius: 20px;
        text-align: unset;
        border-color: rgb(220,220,220);
        box-shadow: 0px 1px 1px 1px rgba(0, 0, 0, 0.2);
    }
</style>
 <br>
<div class="cover">
<br><br>
<div class="lorange lblue">Hello {{request.user.first_name}},</div>

<br>
<div class="lorange">Invest in Million Token Today</div>
<br>
{% if bid == False %}
<div class="lorange">  You have no active bid. Kindly bid for one <a href="{% url 'Bid:create' %}">right here</a></div>

{% else %}
{% if bid.processed %}
{% if bid.successful %}
<div class="lorange"> Your bid was successful!!!
<br><br><br>
<div class="lblue">
<div>number of tokens received: &emsp;&emsp;<span id="number_of_tokens_allotted">{{bid.successful.number_of_tokens_allotted}}</span></div><br>

<div>number of tokens bid for: &emsp;&emsp;<span id="number_of_tokens">{{bid.number_of_tokens}}</span></div><br>
<div>Price per token : &emsp;&emsp;<span id="price_per_token">{{bid.price_per_token}}</span></div><br>
<div>Total Due : &emsp;&emsp;<span id="total_due">{{bid.successful.total_due}}</span></div>
</div>
</div>
{% else %}
<div class="lorange"> Sorry, your bid was unsuccessful</div><br><br><br>
{% endif %}

{% else %}
<div class="lorange"> You have an active bid for MillionToken 
<br><br><br>
<div class="lblue" >
<div>number of tokens bid for: &emsp;&emsp;<span id="number_of_tokens">{{bid.number_of_tokens}}</span></div><br>
<div>Price per token : &emsp;&emsp;<span id="price_per_token">{{bid.price_per_token}}</span></div>
</div>
</div>
{% endif %}
<br><br><br>
<div class="lorange"><a href="{% url 'Bid:delete' %}"><button>DELETE</button></a></div>

{% endif %}
<br>


<br><br>
<div class="lorange"><a href="{% url 'Users:log-out' %}"><button>LOG OUT</button></a></div>

</div>
<br><br><br><br><br><br>
<script type="text/javascript">
    function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
var list = [document.getElementById('total_due') || false,
        document.getElementById('price_per_token') || false,
        document.getElementById('number_of_tokens') || false,
        document.getElementById('number_of_tokens_allotted') || false,
        ]
for (each in list){
    if (each){
        list[each].innerHTML = numberWithCommas(parseInt(list[each].innerHTML))
    }
}
</script>
{% endblock %}

SwapFashions/Users/templates/Users/sign_in.html
{% extends 'Users/base.html' %}
{% block content %}
{% load static %}

 <br>
<div class="menubuttons" style="border-radius: 20px;text-align: unset;font-weight: normal;border-color: rgb(220,220,220);box-shadow: 0px 1px 1px 1px rgba(0, 0, 0, 0.2);">

<br><br>
<div style="color: orange;font-weight: bold;text-align: center;font-size: 130%;"> Log In </div>
<br>
<div style="color: grey;text-align:center;" class="content">
	Welcome to DigiCentra<br> Please log in up here
</div><br><br>
<div style="width: 20%;margin: auto;">
<form action="{% url 'Users:sign-in' %}" method="POST">
						{{ form.as_p }}
					{% csrf_token %}
<button type="submit" style="background-color:orange;color: white;font-size: 100%;font-weight: bold;" class="linestyle" >Log In</button>
      
</form>
<br><br><br>
<div>Don't have an account? <a href="{% url 'Users:sign-up' %}">sign-up</a>
</div>
<br><br><br><br><br><br>
</div>

</div>

{% endblock %}

SwapFashions/Users/templates/Users/sign_up.html
{% extends 'Users/base.html' %}
{% block content %}
{% load static %}

 <br>
<div class="menubuttons" style="border-radius: 20px;text-align: unset;font-weight: normal;border-color: rgb(220,220,220);box-shadow: 0px 1px 1px 1px rgba(0, 0, 0, 0.2);">

<br><br>
<div style="color: orange;font-weight: bold;text-align: center;font-size: 130%;"> Sign Up </div>
<br>
<div style="color: grey;text-align:center;" class="content">
	Welcome to DigiCentra<br> Please Sign up here
</div><br><br>
<form action="{% url 'Users:sign-up' %}" method="POST">
						{{ form.as_p }}
					{% csrf_token %}
<button type="submit" style="background-color:orange;color: white;font-size: 100%;font-weight: bold;" class="linestyle" >Sign Up</button>
      
</form>
<br><br><br>
</div>


{% endblock %}